import os
os.system('pip install bs4')
os.system('pip install urllib3')
os.system('pip install lxml')
os.system('pip install gc')
os.system('pip install certifi')
os.system('pip install requests')
os.system('pip install tqdm.auto')
os.system('pip install colorama')
os.system('clear')
print('Packages have been successfully installed, you can now run the script using: python dissec.py')
